name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/checkout@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      run: gradle/build

    - name: Test with Gradle
      run: gradle/test

